apiVersion: v1
kind: PersistentVolume
metadata:
  name: workshop-inventory-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/workshop-inventory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workshop-inventory-photos-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/workshop-inventory/photos 