apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop-inventory-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop-inventory-photos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 