apiVersion: v1
kind: Service
metadata:
  name: workshop-inventory
  labels:
    app: workshop-inventory
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: workshop-inventory 